runtime: python39

# F1 is too weak to run the backend, so F2 is required.
instance_class: F2

handlers:
  # This configures Google App Engine to serve the Looking Glass app.
  - url: /app
    static_dir: app

  # This routes all requests not caught above to the Looking Glass server.
  - url: /.*
    script: auto

# A custom entry point is required for this app
entrypoint: python3 -m server
