# Google Cloud Build configuration

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Use a Python container to generate the .env file.
  - name: "python"
    # Start the setup script in Python. Also ask it to make a .env file.
    entrypoint: 'python'
    args: ['setup.py', '-e']
    # Pass the environment variables from the build configuration.
    # These variables will be visible to Cloud Build, which will pass them to App Engine.
    env:
      - 'LG_BOT_TOKEN=$_BOT_TOKEN'
      - 'LG_APP_URL=$_APP_URL'
      - 'LG_SERVER_URL=$_SERVER_URL'
      - 'LG_SERVER_PORT=$_PORT'

  # Use a container with Google's Cloud SDK to deploy the backend to App Engine.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    # Start bash with the arguments below.
    entrypoint: 'bash'
    # This generates a .env file and deploys the project to App Engine.
    args: ['-c', 'gcloud config set project ${_PROJECT_ID} && gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --project=${_PROJECT_ID}']
    env:
      # Set the project ID.
      - 'PROJECT_ID=$_PROJECT_ID'